# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
source 'git@pkg.poizon.com:duapp/iOS/DUSpecs.git'

target 'DUExcelDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'DUExcelView', :path => '../'

  # Pods for DUExcelDemo

end
